config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get 'login'  => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  namespace :crm do
    resources :users
  end

  namespace :crm do
    resources :accesses
  end

  namespace :crm do
    resources :domains
  end

end

app/models/crm.rb
module Crm
  def self.table_name_prefix
    'crm_'
  end
end

app/models/crm/access.rb
class Crm::Access < ActiveRecord::Base
	has_many :domain
end

app/models/crm/domain.rb
class Crm::Domain < ActiveRecord::Base
	belongs_to  :access

	validates :name, :presence => {:message => 'Укажите имя домена'}, :uniqueness => {:message => 'Такой домен уже добавлен'}
end

app/models/crm/user.rb
class Crm::User < ActiveRecord::Base
	after_destroy :ensure_an_crm_remains

	validates	:nickname, presence: true
	validates	:email, presence: true, uniqueness: true

	has_secure_password

	def self.search(search)
		if search
			wildcard_search = "%#{search}%"
			where("nickname LIKE ? OR email LIKE ?", wildcard_search, wildcard_search)
		else
			all
		end
	end

	private
		def ensure_an_crm_remains
			if Crm::User.count.zero?
				raise "Последний пользователь не может быть удален"
		end
	end
end

app/controllers/crm/accesses_controller.rb
class Crm::AccessesController < ApplicationController
  before_action :set_crm_access, only: [:show, :edit, :update, :destroy]

  # GET /crm/accesses
  def index
    @crm_accesses = Crm::Access.all
  end

  # GET /crm/accesses/1
  def show
  end

  # GET /crm/accesses/new
  def new
    @crm_access = Crm::Access.new
  end

  # GET /crm/accesses/1/edit
  def edit
  end

  # POST /crm/accesses
  def create
    @crm_access = Crm::Access.new(crm_access_params)

    if @crm_access.save
      redirect_to @crm_access, notice: 'Access was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /crm/accesses/1
  def update
    if @crm_access.update(crm_access_params)
      redirect_to @crm_access, notice: 'Access was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /crm/accesses/1
  def destroy
    @crm_access.destroy
    redirect_to crm_accesses_url, notice: 'Access was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crm_access
      @crm_access = Crm::Access.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def crm_access_params
      params[:crm_access]
    end
end

app/controllers/crm/domains_controller.rb
class Crm::DomainsController < ApplicationController
  before_action :set_crm_domain, only: [:show, :edit, :update, :destroy]

  # GET /crm/domains
  # GET /crm/domains.json
  def index
    @crm_domains = Crm::Domain.all
  end


  # GET /crm/domains/new
  def new
    @crm_domain = Crm::Domain.new
  end

  # GET /crm/domains/1/edit
  def edit
  end

  # POST /crm/domains
  # POST /crm/domains.json
  def create
    @crm_domain = Crm::Domain.new(crm_domain_params)

    respond_to do |format|
      if @crm_domain.save
        format.html { redirect_to @crm_domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @crm_domain }
      else
        format.html { render :new }
        format.json { render json: @crm_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crm/domains/1
  # PATCH/PUT /crm/domains/1.json
  def update
    respond_to do |format|
      if @crm_domain.update(crm_domain_params)
        format.html { redirect_to edit_crm_domain_path(@crm_domain), notice: 'Информация по домену обновлена.' }
        format.json { render :show, status: :ok, location: @crm_domain }
      else
        format.html { render :edit }
        format.json { render json: @crm_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crm/domains/1
  # DELETE /crm/domains/1.json
  def destroy
    @crm_domain.destroy
    respond_to do |format|
      format.html { redirect_to crm_domains_url, notice: 'Домен удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crm_domain
      @crm_domain = Crm::Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crm_domain_params
      params[:crm_domain].permit!
    end
end

app/controllers/crm/users_controller.rb
class Crm::UsersController < ApplicationController
  before_action :set_crm_user, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /crm/users
  def index
    respond_to do |format|
      format.html
      format.js do

        WillPaginate.per_page = params[:limit].blank? ? 1000000 : params[:limit].to_i

        @crm_users = Crm::User
          .search(params[:qsearch])
          .order(sort_column + ' ' + sort_direction)
          .paginate(:page => params[:page] || 1)
      end
    end

  end

  # GET /crm/users/new
  def new
    @crm_user = Crm::User.new
  end

  # GET /crm/users/1/edit
  def edit
  end

  # POST /crm/users
  def create
    @crm_user = Crm::User.new(crm_user_params)

    respond_to do |format|
      if @crm_user.save
        if(!params[:continue].blank?)
          format.html { redirect_to edit_crm_user_path(@crm_user), notice: 'Пользователь создан.' }
          format.json { render :show, status: :created, location: @crm_user }

        else
          format.html { redirect_to crm_users_path, notice: "Пользователь «#{@crm_user.nickname}» создан." }
          format.json { render :show, status: :created, location: @crm_user }
        end

      else
        format.html { render :new }
        format.json { render json: @crm_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crm/users/1
  def update
    respond_to do |format|
      if @crm_user.update(crm_user_params)
        if(!params[:continue].blank?)
          format.html { redirect_to edit_crm_user_path(@crm_user), notice: 'Информация по пользователю обновлена.' }
          format.json { render :show, status: :created, location: @crm_user }

        else
          format.html { redirect_to crm_users_path, notice: "Информация по пользователю «#{@crm_user.nickname}» обновлена." }
          format.json { render :show, status: :created, location: @crm_user }
        end

      else
        format.html { render :edit }
        format.json { render json: @crm_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crm/users/1
  def destroy
    @crm_user.destroy
    redirect_to crm_users_url, notice: 'Пользователь удален.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crm_user
      @crm_user = Crm::User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def crm_user_params
      params.require(:crm_user).permit(:nickname, :email, :password_digest, :password, :password_confirmation)
    end

    def sort_column
      Crm::User.column_names.include?(params[:sort_column]) ? params[:sort_column] : "nickname"
    end

    def sort_direction
      %w[asc desc].include?(params[:sort_direction]) ? params[:sort_direction] : "asc"
    end
end

app/helpers/crm/accesses_helper.rb
module Crm::AccessesHelper
end

app/helpers/crm/domains_helper.rb
module Crm::DomainsHelper
end

app/helpers/crm/users_helper.rb
module Crm::UsersHelper
end

app/views/crm/_msg.html.erb
<% if flash[:alert] %>
  <span class="message-alert message" style="padding:20px;"><%= flash[:alert] %></span>

<% elsif flash[:notice] %>
  <span class="message-notice message" style="padding:20px;"><%= flash[:notice] %></span>

<% end %>

app/views/crm/_msg_item_error.html.erb
<% if object.errors.any? %>
	<div class="message message-edit message-alert">
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/crm/_pagination.html.erb
<ul id="pagination" style="float: right; margin: 5px 0;">
	<li>Отображать по</li>
	<li><a href="#" data-limit="25" >25</a></li>
	<li><a href="#" data-limit="50" >50</a></li>
	<li><a href="#" data-limit="75" >75</a></li>
	<li><a href="#" data-limit="100" >100</a></li>
	<li><a href="#" data-limit="" class="current">все</a></li>
</ul>
<script type="text/javascript">
	$("#pagination a").click(function(){
		$("#pagination a").removeClass('current');
		$(this).addClass('current');

		items_list( filter());
		return false;
	})
</script>

app/views/crm/_search_form.html.erb
<div id="search">
	<div class="loading"></div>
	<%= form_tag form_action, :method => 'get', :id => "item_search" do %>
		<%= text_field_tag "qsearch", params[:qsearch], placeholder: "Что ищем?" %>
		<label><%= check_box_tag 'qsearch_nofilter', 1 %>Не учитывать фильтры</label>
	<% end %>
</div>

app/views/crm/_top.html.erb
<div id="topbar">
  <script type="text/javascript">
      $(document).ready(function(){
          $("#topbar-menu li.noempty a").click(function(e){
              if ($(this).closest("li").is(".hover")) {
                  $(this).closest("li").removeClass("hover").find("ul").slideUp();
              } else {
                  $("body").click();
                  $(this).closest("li").addClass("hover").find("ul").slideDown();
              }
              e.stopPropagation();
              return true;
          });
          $("body").click(function(){
              $("#topbar-menu li.noempty").removeClass("hover").find("ul").slideUp();
          });
      });
  </script>
  <ul id="topbar-menu">
    <li class="noempty"><a href="javascript:void(0);" style="background-image: url(/crm/img/add1.png)"><ins></ins><span>Добавить</span></a>
      <ul class="add-links">
        <li><a href="<%= new_crm_domain_path %>" <%== controller_name == 'domains' ? "class='current'" : "" %> id="add-new-domain">Домен</a></li>
        <li><a href="<%= new_crm_access_path %>" <%== controller_name == 'accesses' ? "class='current'" : "" %> id="add-new-access">Доступы</a></li>
        <li><a href="<%= new_crm_user_path %>" <%== controller_name == 'users' ? "class='current'" : "" %> id="add-new-access">Пользователя</a></li>
      </ul>
    </li>
    <li><a class="<%= controller_name == 'domains' ? 'current' : '' %>" href="<%= crm_domains_path %>" style="background-image: url(/crm/img/list.png)">Домены</a></li>
    <li><a class="<%= controller_name == 'accesses' ? 'current' : '' %>" href="<%= crm_accesses_path %>" style="background-image: url(/crm/img/list.png)">Доступы</a></li>
    <li><a class="<%= controller_name == 'users' ? 'current' : '' %>" href="<%= crm_users_path %>" style="background-image: url(/crm/img/list.png)">Пользователи</a></li>


  </ul>
  <div id="auth-logged">
    Здравствуйте, <a href="<%= edit_crm_user_path(current_user) %>" id="auth-logged-username"><%= current_user.nickname %></a>

  </div>
</div>