config/routes.rb
Rails.application.routes.draw do

  controller :sessions do
    get 'login'  => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  namespace :crm do
    resources :users
  end

  namespace :crm do
    resources :accesses
  end

  namespace :crm do
    resources :domains
  end

end

app/models/crm.rb
module Crm
  def self.table_name_prefix
    'crm_'
  end
end

app/models/crm/access.rb
class Crm::Access < ActiveRecord::Base
	has_many :domain
end

app/models/crm/domain.rb
class Crm::Domain < ActiveRecord::Base
	belongs_to  :access

	validates :name, :presence => {:message => 'Укажите имя домена'}, :uniqueness => {:message => 'Такой домен уже добавлен'}
end

app/models/crm/user.rb
class Crm::User < ActiveRecord::Base
	after_destroy :ensure_an_crm_remains

	validates	:nickname, presence: true
	validates	:email, presence: true, uniqueness: true

	has_secure_password

	def self.search(search)
		if search
			wildcard_search = "%#{search}%"
			where("nickname LIKE ? OR email LIKE ?", wildcard_search, wildcard_search)
		else
			all
		end
	end

	private
		def ensure_an_crm_remains
			if Crm::User.count.zero?
				raise "Последний пользователь не может быть удален"
		end
	end
end

app/controllers/crm/accesses_controller.rb
class Crm::AccessesController < ApplicationController
  before_action :set_crm_access, only: [:show, :edit, :update, :destroy]

  # GET /crm/accesses
  def index
    @crm_accesses = Crm::Access.all
  end

  # GET /crm/accesses/1
  def show
  end

  # GET /crm/accesses/new
  def new
    @crm_access = Crm::Access.new
  end

  # GET /crm/accesses/1/edit
  def edit
  end

  # POST /crm/accesses
  def create
    @crm_access = Crm::Access.new(crm_access_params)

    if @crm_access.save
      redirect_to @crm_access, notice: 'Access was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /crm/accesses/1
  def update
    if @crm_access.update(crm_access_params)
      redirect_to @crm_access, notice: 'Access was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /crm/accesses/1
  def destroy
    @crm_access.destroy
    redirect_to crm_accesses_url, notice: 'Access was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crm_access
      @crm_access = Crm::Access.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def crm_access_params
      params[:crm_access]
    end
end

app/controllers/crm/domains_controller.rb
class Crm::DomainsController < ApplicationController
  before_action :set_crm_domain, only: [:show, :edit, :update, :destroy]

  # GET /crm/domains
  # GET /crm/domains.json
  def index
    @crm_domains = Crm::Domain.all
  end


  # GET /crm/domains/new
  def new
    @crm_domain = Crm::Domain.new
  end

  # GET /crm/domains/1/edit
  def edit
  end

  # POST /crm/domains
  # POST /crm/domains.json
  def create
    @crm_domain = Crm::Domain.new(crm_domain_params)

    respond_to do |format|
      if @crm_domain.save
        format.html { redirect_to @crm_domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @crm_domain }
      else
        format.html { render :new }
        format.json { render json: @crm_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crm/domains/1
  # PATCH/PUT /crm/domains/1.json
  def update
    respond_to do |format|
      if @crm_domain.update(crm_domain_params)
        format.html { redirect_to edit_crm_domain_path(@crm_domain), notice: 'Информация по домену обновлена.' }
        format.json { render :show, status: :ok, location: @crm_domain }
      else
        format.html { render :edit }
        format.json { render json: @crm_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crm/domains/1
  # DELETE /crm/domains/1.json
  def destroy
    @crm_domain.destroy
    respond_to do |format|
      format.html { redirect_to crm_domains_url, notice: 'Домен удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crm_domain
      @crm_domain = Crm::Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crm_domain_params
      params[:crm_domain].permit!
    end
end

app/controllers/crm/users_controller.rb
class Crm::UsersController < ApplicationController
  before_action :set_crm_user, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /crm/users
  def index
    respond_to do |format|
      format.html
      format.js do

        WillPaginate.per_page = params[:limit].blank? ? 1000000 : params[:limit].to_i

        @crm_users = Crm::User
          .search(params[:qsearch])
          .order(sort_column + ' ' + sort_direction)
          .paginate(:page => params[:page] || 1)
      end
    end

  end

  # GET /crm/users/new
  def new
    @crm_user = Crm::User.new
  end

  # GET /crm/users/1/edit
  def edit
  end

  # POST /crm/users
  def create
    @crm_user = Crm::User.new(crm_user_params)

    respond_to do |format|
      if @crm_user.save
        if(!params[:continue].blank?)
          format.html { redirect_to edit_crm_user_path(@crm_user), notice: 'Пользователь создан.' }
          format.json { render :show, status: :created, location: @crm_user }

        else
          format.html { redirect_to crm_users_path, notice: "Пользователь «#{@crm_user.nickname}» создан." }
          format.json { render :show, status: :created, location: @crm_user }
        end

      else
        format.html { render :new }
        format.json { render json: @crm_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crm/users/1
  def update
    respond_to do |format|
      if @crm_user.update(crm_user_params)
        if(!params[:continue].blank?)
          format.html { redirect_to edit_crm_user_path(@crm_user), notice: 'Информация по пользователю обновлена.' }
          format.json { render :show, status: :created, location: @crm_user }

        else
          format.html { redirect_to crm_users_path, notice: "Информация по пользователю «#{@crm_user.nickname}» обновлена." }
          format.json { render :show, status: :created, location: @crm_user }
        end

      else
        format.html { render :edit }
        format.json { render json: @crm_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crm/users/1
  def destroy
    @crm_user.destroy
    redirect_to crm_users_url, notice: 'Пользователь удален.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crm_user
      @crm_user = Crm::User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def crm_user_params
      params.require(:crm_user).permit(:nickname, :email, :password_digest, :password, :password_confirmation)
    end

    def sort_column
      Crm::User.column_names.include?(params[:sort_column]) ? params[:sort_column] : "nickname"
    end

    def sort_direction
      %w[asc desc].include?(params[:sort_direction]) ? params[:sort_direction] : "asc"
    end
end

app/helpers/crm/accesses_helper.rb
module Crm::AccessesHelper
end

app/helpers/crm/domains_helper.rb
module Crm::DomainsHelper
end

app/helpers/crm/users_helper.rb
module Crm::UsersHelper
end

app/views/crm/domains/_domain.html.erb
<tr onClick="javascript:document.location.href='<%= edit_crm_domain_path(domain) %>'" class="yellow items" data-item-id="<%= domain.id %>">
  <td><input type="checkbox" class="chb_selectItem" value="<%= domain.id %>"/></td>
  <td><%= domain.name %></td>
  <td><%= domain.regdate ? domain.regdate.strftime("%d.%m.%Y") : '-' %></td>
  <td><%= domain.paiddate ? domain.paiddate.strftime("%d.%m.%Y") : '-' %></td>
  <td><a class="action" href="<%= edit_crm_domain_path(domain) %>" title="Смотреть"><img src="/crm/img/edit.png" width="16" height="16" alt=""></a></td>
</tr>

app/views/crm/domains/_form.html.erb
<h1><%== params[:id] ? "Редактирование карточки домена «" + @crm_domain.name + "»" : "Добавление нового домена" %></h1>
<div class="rightCol">
	<% if params[:id] %>
		<%= link_to 'Удалить', crm_domain_path(@crm_domain), :confirm => "Вы уверены что хотите удалить домен?", :method => :delete, :class => 'rightBut', :id => 'right-delete' %>
	<% end %>

	<%= link_to 'Сохранить и продолжить', '', :class => 'rightBut', :id => 'save-and-continue' %>
	<%= link_to 'Сохранить и закрыть', '', :class => 'rightBut', :id => 'save-and-exit' %>

	<br/>
	<a href="<%= crm_domains_path %>" class="rightBut" id="right-delete">К списку доменов</a>

</div>
<div class="leftCol">
	<ul class="tabs-menu">
		<li style="z-index:10;" class="current"><a href="#" style="background-image: url(/crm/img/icon_calend.png);">Карточка домена</a><ins></ins></li>
	</ul>
	<div class="anketa-block">

		<%= render "Crm/msg_item_error", object: @crm_domain %>
		<%= render 'crm/msg' %>

		<%= simple_form_for([@crm_domain]) do |f| %>
			<input type="hidden" name="continue" value="0" />
			<table class="anketa float-table-3col">
				<tr>
					<td>
						<label>
							<%= f.input :name, label: 'Домен'%>
						</label>
					</td>
					<td>
						<label>
                            <%= f.input :regdate, label: 'Дата регистрации'%>
						</label>
					</td>
					<td>
						<label>
                          <%= f.input :paiddate, label: 'Оплачен до'%>
						</label>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<%= f.input :comment, label: 'Комментарий' %>
					</td>
				</tr>
			</table>
		<% end %>
	</div>
</div>


<script type="text/javascript">
	$("#save-and-continue").click(function(){
		$("input[name=continue]").val(1);
		$(".anketa-block form").submit();
		return false;
	})
	$("#save-and-exit").click(function(){
		$("input[name=continue]").val(0);
		$(".anketa-block form").submit();
		return false;
	})
</script>

app/views/crm/domains/create.js.erb
$("#container").html("<%= j render(@crm_domain) %>")

app/views/crm/domains/edit.html.erb
<%= render 'form' %>


<%# render 'form' %>

<%# link_to 'Show', @domain %> |
<%# link_to 'Back', domains_path %>

app/views/crm/domains/index.html.erb
<%= render 'crm/msg' %>

<div id="container">
	<h1>
		Домены
	</h1>

	<%= render 'crm/search_form' %>

	<div id="list-container">
		<table id="list">
			<col width="10" />
			<col width="auto" />
			<col width="150" />
			<col width="150" />
            <col width="10" />
			<thead>
			<tr>
				<th><input type="checkbox" id="chb_toogleAllChecked"/></th>
				<th>
					<div data-order="name">
						<a class="az" href="#"></a>
						<a class="za" href="#"></a>
						<a class="sort" href="#">Домен</a>
					</div>
				</th>
				<th>
					<div data-order="text">
						<a class="az" href="#"></a>
						<a class="za" href="#"></a>
						<a class="sort" href="#">Дата регистрации</a>
					</div>
				</th>
				<th>
					<div data-order="comment">
						<a class="az" href="#"></a>
						<a class="za" href="#"></a>
						<a class="sort" href="#">Оплачен до</a>
					</div>
				</th>
				<th>
				</th>
			</tr>
			 </thead>
			<tbody id="list-items"></tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
		CONTROLLER = '<%= controller_name %>';

		function filter(add_filter){
			var filter = {};
			filter['container_items'] = 'list-items';

			if(order){
				filter['order']	= order;
				filter['order_type'] = order_type;
			}
			filter['id_handler'] =  $("input[name=filter_input_id_handler]:checked").length? $("input[name=filter_input_id_handler]:checked").val() : 0;

			filter['qsearch_nofilter'] = $("input[name=qsearch_nofilter]:checked").length ? 1 : 0;
			filter['limit'] = parseInt( $("#pagination a.current").data('limit') );

			return jQuery.extend(filter, add_filter);
		}



		$(document).ready(function(){
			items_list( filter() );

			// checkbox entity click
			$("#list").on("click", "tr td input", function(e){
				e.stopPropagation();
			});
		});
</script>

app/views/crm/domains/index.js.erb
$('#list-items').empty().append('<%= j render(@crm_domains) %>');

app/views/crm/domains/new.html.erb
<%= render 'form' %>